import java.time.LocalDate;
public class ClassePrincipal {
	public static void main(String[] args) {

		System.out.println();
		Pessoa pessoa1 = new Pessoa();
		pessoa1.nome = "Pedro";
		pessoa1.idade = 15;
		System.out.println("Pessoa 1:");
		System.out.println("Nome: " + pessoa1.nome);
		System.out.println("Idade: " + pessoa1.idade);
		Pessoa pessoa2 = new Pessoa();
		pessoa2.nome = "Cadu";
		pessoa2.idade = 17;
		System.out.println("Pessoa 2:");
		System.out.println("Nome: " + pessoa2.nome);
		System.out.println("Idade: " + pessoa2.idade);

		System.out.println();
		Carro carro1 = new Carro();
		carro1.marca = "Chevrolet";
		carro1.modelo = "Onix";
		carro1.ano = 2023;
		System.out.println("Carro 1:");
		System.out.println("Marca: " + carro1.marca);
		System.out.println("Modelo: " + carro1.modelo);
		System.out.println("Ano: " + carro1.ano);
		Carro carro2 = new Carro();
		carro2.marca = "Wolkswagem";
		carro2.modelo = "Gol";
		carro2.ano = 2021;
		System.out.println("Carro 2:");
		System.out.println("Marca: " + carro2.marca);
		System.out.println("Modelo: " + carro2.modelo);
		System.out.println("Ano: " + carro2.ano);
		Carro carro3 = new Carro();
		carro3.marca = "Fiat";
		carro3.modelo = "Uno";
		carro3.ano = 2019;
		System.out.println("Carro 3:");
		System.out.println("Marca: " + carro3.marca);
		System.out.println("Modelo: " + carro3.modelo);
		System.out.println("Ano: " + carro3.ano);

		System.out.println();
		Livro livro1 = new Livro();
		livro1.titulo = "1984";
		livro1.autor = "Geroge Orwell";
		livro1.anoDePublicacao = 1949;
		System.out.println("Livro 1:");
		System.out.println("Título: " + livro1.titulo);
		System.out.println("Autor: " + livro1.autor);
		System.out.println("Ano de publicação: " + livro1.anoDePublicacao);
		Livro livro2 = new Livro();
		livro2.titulo = "O hobbit";
		livro2.autor = "J. R. r. Tolkien";
		livro2.anoDePublicacao = 1937;
		System.out.println("Livro 2:");
		System.out.println("Título: " + livro2.titulo);
		System.out.println("Autor: " + livro2.autor);
		System.out.println("Ano de publicação: " + livro2.anoDePublicacao);
		Livro livro3 = new Livro();
		livro3.titulo = "Extraordinário";
		livro3.autor = "R. J. Palacio";
		livro3.anoDePublicacao = 2012;
		System.out.println("Livro 3:");
		System.out.println("Título: " + livro3.titulo);
		System.out.println("Autor: " + livro3.autor);
		System.out.println("Ano de publicação: " + livro3.anoDePublicacao);

		System.out.println();
		Aluno aluno1 = new Aluno();
		aluno1.nome = "Maria";
		aluno1.matricula = 126533;
		aluno1.notaFinal = 9.75;
		System.out.println("Aluno 1:");
		System.out.println("Nome: " + aluno1.nome);
		System.out.println("Matrícula: " + aluno1.matricula);
		System.out.println("Nota final: " + aluno1.notaFinal);
		Aluno aluno2 = new Aluno();
		aluno2.nome = "Julia";
		aluno2.matricula = 5884699;
		aluno2.notaFinal = 8.10;
		System.out.println("Aluno 2:");
		System.out.println("Nome: " + aluno2.nome);
		System.out.println("Matrícula: " + aluno2.matricula);
		System.out.println("Nota final: " + aluno2.notaFinal);
		Aluno aluno3 = new Aluno();
		aluno3.nome = "Roberto";
		aluno3.matricula = 7986245;
		aluno3.notaFinal = 6.98;
		System.out.println("Aluno 3:");
		System.out.println("Nome: " + aluno3.nome);
		System.out.println("Matrícula: " + aluno3.matricula);
		System.out.println("Nota final: " + aluno3.notaFinal);
		Aluno aluno4 = new Aluno();
		aluno4.nome = "Roberto";
		aluno4.matricula = 99658;
		aluno4.notaFinal = 7.45;
		System.out.println("Aluno 4:");
		System.out.println("Nome: " + aluno4.nome);
		System.out.println("Matrícula: " + aluno4.matricula);
		System.out.println("Nota final: " + aluno4.notaFinal);

		System.out.println();
		Roda roda1 = new Roda();
		roda1.id = 12345;
		roda1.diametro = 8;
		roda1.raio = roda1.diametro / 2;
		roda1.material = "Metal";
		System.out.println("Roda 1:");
		System.out.println("ID: " + roda1.id);
		System.out.println("Diâmetro: " + roda1.diametro);
		System.out.println("Raio: " + roda1.raio);
		System.out.println("Material: " + roda1.material);
		Roda roda2 = new Roda();
		roda2.id = 67890;
		roda2.diametro = 10;
		roda2.raio = roda2.diametro / 2;
		roda2.material = "Borracha";
		System.out.println("Roda 2:");
		System.out.println("ID: " + roda2.id);
		System.out.println("Diâmetro: " + roda2.diametro);
		System.out.println("Raio: " + roda2.raio);
		System.out.println("Material: " + roda2.material);
		Roda roda3 = new Roda();
		roda3.id = 11121;
		roda3.diametro = 12;
		roda3.raio = roda3.diametro / 2;
		roda3.material = "Plástico";
		System.out.println("Roda 3:");
		System.out.println("ID: " + roda3.id);
		System.out.println("Diâmetro: " + roda3.diametro);
		System.out.println("Raio: " + roda3.raio);
		System.out.println("Material: " + roda3.material);
		Roda roda4 = new Roda();
		roda4.id = 54321;
		roda4.diametro = 15;
		roda4.raio = roda4.diametro / 2;
		roda4.material = "Alumínio";
		System.out.println("Roda 4:");
		System.out.println("ID: " + roda4.id);
		System.out.println("Diâmetro: " + roda4.diametro);
		System.out.println("Raio: " + roda4.raio);
		System.out.println("Material: " + roda4.material);
		
		System.out.println();
        Animal animal1 = new Animal();
        animal1.nome = "Rex";
        animal1.raca = "Pastor Alemão";
        animal1.idade = 5;
        System.out.println("Animal 1:");
        System.out.println("Nome: " + animal1.nome);
        System.out.println("Raça: " + animal1.raca);
        System.out.println("Idade: " + animal1.idade);
        Animal animal2 = new Animal();
        animal2.nome = "Mia";
        animal2.raca = "Siamês";
        animal2.idade = 3;
        System.out.println("Animal 2:");
        System.out.println("Nome: " + animal2.nome);
        System.out.println("Raça: " + animal2.raca);
        System.out.println("Idade: " + animal2.idade);
        Animal animal3 = new Animal();
        animal3.nome = "Thor";
        animal3.raca = "Golden Retriever";
        animal3.idade = 4;
        System.out.println("Animal 3:");
        System.out.println("Nome: " + animal3.nome);
        System.out.println("Raça: " + animal3.raca);
        System.out.println("Idade: " + animal3.idade);
        Animal animal4 = new Animal();
        animal4.nome = "Nina";
        animal4.raca = "Poodle";
        animal4.idade = 2;
        System.out.println("Animal 4:");
        System.out.println("Nome: " + animal4.nome);
        System.out.println("Raça: " + animal4.raca);
        System.out.println("Idade: " + animal4.idade);
        
        System.out.println();
        Endereco endereco1 = new Endereco();
        endereco1.rua = "Av. Paulista";
        endereco1.numero = 1000;
        endereco1.cidade = "São Paulo";
        System.out.println("Endereço 1:");
        System.out.println("Rua: " + endereco1.rua);
        System.out.println("Número: " + endereco1.numero);
        System.out.println("Cidade: " + endereco1.cidade);
        Endereco endereco2 = new Endereco();
        endereco2.rua = "Rua das Flores";
        endereco2.numero = 250;
        endereco2.cidade = "Curitiba";
        System.out.println("Endereço 2:");
        System.out.println("Rua: " + endereco2.rua);
        System.out.println("Número: " + endereco2.numero);
        System.out.println("Cidade: " + endereco2.cidade);
        Endereco endereco3 = new Endereco();
        endereco3.rua = "Av. Beira Mar";
        endereco3.numero = 500;
        endereco3.cidade = "Rio de Janeiro";
        System.out.println("Endereço 3:");
        System.out.println("Rua: " + endereco3.rua);
        System.out.println("Número: " + endereco3.numero);
        System.out.println("Cidade: " + endereco3.cidade);
        Endereco endereco4 = new Endereco();
        endereco4.rua = "Rua Central";
        endereco4.numero = 77;
        endereco4.cidade = "Porto Alegre";
        System.out.println("Endereço 4:");
        System.out.println("Rua: " + endereco4.rua);
        System.out.println("Número: " + endereco4.numero);
        System.out.println("Cidade: " + endereco4.cidade);
        
        System.out.println();
        ContaBancaria conta1 = new ContaBancaria();
        conta1.numeroDaConta = 123456;
        conta1.saldo = 2500.75;
        System.out.println("Conta 1:");
        System.out.println("Saldo: " + conta1.saldo);
        ContaBancaria conta2 = new ContaBancaria();
        conta2.numeroDaConta = 789012;
        conta2.saldo = 5000.50;
        System.out.println("Conta 2:");
        System.out.println("Saldo: " + conta2.saldo);
        
        System.out.println();
        Funcionario func1 = new Funcionario();
        func1.nome = "Carlos Silva";
        func1.salario = 3500.00;
        func1.cargo = "Analista de Sistemas";
        System.out.println("Funcionário 1:");
        System.out.println("Nome: " + func1.nome);
        System.out.println("Salário: R$ " + func1.salario);
        System.out.println("Cargo: " + func1.cargo);
        Funcionario func2 = new Funcionario();
        func2.nome = "Ana Souza";
        func2.salario = 4500.00;
        func2.cargo = "Gerente de Projetos";
        System.out.println("Funcionário 2:");
        System.out.println("Nome: " + func2.nome);
        System.out.println("Salário: R$ " + func2.salario);
        System.out.println("Cargo: " + func2.cargo);
        Funcionario func3 = new Funcionario();
        func3.nome = "Marcos Pereira";
        func3.salario = 2800.00;
        func3.cargo = "Desenvolvedor Júnior";
        System.out.println("Funcionário 3:");
        System.out.println("Nome: " + func3.nome);
        System.out.println("Salário: R$ " + func3.salario);
        System.out.println("Cargo: " + func3.cargo);
        Funcionario func4 = new Funcionario();
        func4.nome = "Beatriz Almeida";
        func4.salario = 6000.00;
        func4.cargo = "Diretora de TI";
        System.out.println("Funcionário 4:");
        System.out.println("Nome: " + func4.nome);
        System.out.println("Salário: R$ " + func4.salario);
        System.out.println("Cargo: " + func4.cargo);
        
        System.out.println();
        Produto produto1 = new Produto();
        produto1.nome = "Notebook";
        produto1.preco = 4500.00;
        produto1.descricao = "Notebook Gamer com processador i7 e 16GB RAM";
        produto1.quantidadeEstoque = 10;
        System.out.println("Produto 1:");
        System.out.println("Nome: " + produto1.nome);
        System.out.println("Preço: R$ " + produto1.preco);
        System.out.println("Descrição: " + produto1.descricao);
        System.out.println("Quantidade em Estoque: " + produto1.quantidadeEstoque);
        Produto produto2 = new Produto();
        produto2.nome = "Smartphone";
        produto2.preco = 3200.00;
        produto2.descricao = "Smartphone com câmera de 108MP e bateria de longa duração";
        produto2.quantidadeEstoque = 25;
        System.out.println("Produto 2:");
        System.out.println("Nome: " + produto2.nome);
        System.out.println("Preço: R$ " + produto2.preco);
        System.out.println("Descrição: " + produto2.descricao);
        System.out.println("Quantidade em Estoque: " + produto2.quantidadeEstoque);
        Produto produto3 = new Produto();
        produto3.nome = "Fone de Ouvido";
        produto3.preco = 350.00;
        produto3.descricao = "Fone de ouvido Bluetooth com cancelamento de ruído";
        produto3.quantidadeEstoque = 50;
        System.out.println("Produto 3:");
        System.out.println("Nome: " + produto3.nome);
        System.out.println("Preço: R$ " + produto3.preco);
        System.out.println("Descrição: " + produto3.descricao);
        System.out.println("Quantidade em Estoque: " + produto3.quantidadeEstoque);
        Produto produto4 = new Produto();
        produto4.nome = "Monitor";
        produto4.preco = 1200.00;
        produto4.descricao = "Monitor 27 polegadas Full HD com taxa de atualização de 144Hz";
        produto4.quantidadeEstoque = 15;
        System.out.println("Produto 4:");
        System.out.println("Nome: " + produto4.nome);
        System.out.println("Preço: R$ " + produto4.preco);
        System.out.println("Descrição: " + produto4.descricao);
        System.out.println("Quantidade em Estoque: " + produto4.quantidadeEstoque);
        
        System.out.println();
        Emprestimo emprestimo1 = new Emprestimo();
        emprestimo1.valor = 5000.00;
        emprestimo1.dataDeEmprestimo = LocalDate.of(2024, 3, 1);
        emprestimo1.numeroDeParcelas = 12;
        System.out.println("Empréstimo 1:");
        System.out.println("Valor: R$ " + emprestimo1.valor);
        System.out.println("Data do Empréstimo: " + emprestimo1.dataDeEmprestimo);
        System.out.println("Número de Parcelas: " + emprestimo1.numeroDeParcelas);

        Emprestimo emprestimo2 = new Emprestimo();
        emprestimo2.valor = 12000.00;
        emprestimo2.dataDeEmprestimo = LocalDate.of(2024, 2, 15);
        emprestimo2.numeroDeParcelas = 24;
        System.out.println("Empréstimo 2:");
        System.out.println("Valor: R$ " + emprestimo2.valor);
        System.out.println("Data do Empréstimo: " + emprestimo2.dataDeEmprestimo);
        System.out.println("Número de Parcelas: " + emprestimo2.numeroDeParcelas);

        Emprestimo emprestimo3 = new Emprestimo();
        emprestimo3.valor = 3000.00;
        emprestimo3.dataDeEmprestimo = LocalDate.of(2024, 1, 10);
        emprestimo3.numeroDeParcelas = 6;
        System.out.println("Empréstimo 3:");
        System.out.println("Valor: R$ " + emprestimo3.valor);
        System.out.println("Data do Empréstimo: " + emprestimo3.dataDeEmprestimo);
        System.out.println("Número de Parcelas: " + emprestimo3.numeroDeParcelas);
  
        Emprestimo emprestimo4 = new Emprestimo();
        emprestimo4.valor = 20000.00;
        emprestimo4.dataDeEmprestimo = LocalDate.of(2023, 12, 5);
        emprestimo4.numeroDeParcelas = 36;
        System.out.println("Empréstimo 4:");
        System.out.println("Valor: R$ " + emprestimo4.valor);
        System.out.println("Data do Empréstimo: " + emprestimo4.dataDeEmprestimo);
        System.out.println("Número de Parcelas: " + emprestimo4.numeroDeParcelas);
	}
}